name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    
    - name: Install dependencies
      run: go mod tidy

    - name: Test
      run: go test -v ./...
    
    - name: Build
      run: go build -o spaceship.exe -v ./cmd/main.go
    
    - name: Upload an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: executable-file 
        path: ./spaceship.exe
