name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - artifact_name: linux
            os: ubuntu-latest
          - artifact_name: windows
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
        
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go get -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Build
      run: go build -o spaceship.exe -v ./cmd/main.go
    
    - name: Upload an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: spaceship-game-${{ matrix.artifact_name }}
        path: ./spaceship-${{ matrix.artifact_name }}.exe
